### ISSUE TITLE
Errors in zoo.py 

### ISSUE THREAD

**Issue by edoardogiacomello** [dribnet/plat#5]
Hello,
I was running the quickstart code and it gave me this error on Python3.6:
`➜  plat plat sample --model celeba_64.discgen
Traceback (most recent call last):
  File "/home/<username>/.local/bin/plat", line 11, in <module>
    sys.exit(main())
  [...]
  File "/home/<username>/.local/lib/python3.6/site-packages/plat/zoo.py", line 131, in check_model_download
    result = raw_input("Model {} will be downloaded. Continue? [Y/n]".format(model_name))
NameError: name 'raw_input' is not defined
`
renaming "raw_input" to "input" fixed the issue.

I also have another problem about the quickstart code: after the download it tries to make an hard link from the /tmp/ and the /home/.../.plat/zoo/ folder, which are in two different devices in my system so the command fails. Manually moving the file does not skip the download the next time the command is run. Is there any way to make the code work without retargeting my /tmp folder?
Thank you in advance.

**Comment by dribnet** [comment]
Sorry about this. Most of the problems I was getting with this library had to do with how these models were downloaded and deserialized. I'm currently rewriting these parts to use Tensorflow-hub instead, so hopefully this will be fixed in the next release.

Note that the library still works with Keras, pytorch, etc. but the pre-bundled models would be provided in Tensorflow.

If you are still interested in trying this let me know and I can followup to let you know when this is ready for testing.
